"""initial

Revision ID: cec1b17bf48b
Revises: 
Create Date: 2026-01-29 14:58:47.805929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec1b17bf48b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subdomain', sa.String(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_manager_id'), 'user_permissions', ['manager_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_subdomain'), 'user_permissions', ['subdomain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_permissions_subdomain'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_manager_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
